// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHldadrDpSpRw6vHAn0gErCreo2TpZHBA',
    appId: '1:701849516005:web:ec8a03048046619528210c',
    messagingSenderId: '701849516005',
    projectId: 'futurefortunetasks',
    authDomain: 'futurefortunetasks.firebaseapp.com',
    storageBucket: 'futurefortunetasks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IByULRB_Iwu3t5fXsD3xpdbLi7z9rn4',
    appId: '1:701849516005:android:8433a7aaef5cafa128210c',
    messagingSenderId: '701849516005',
    projectId: 'futurefortunetasks',
    storageBucket: 'futurefortunetasks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKqdObNlaPBt5y3LWCUBWVMNZo4JFV_I',
    appId: '1:701849516005:ios:f9138acadbce32ab28210c',
    messagingSenderId: '701849516005',
    projectId: 'futurefortunetasks',
    storageBucket: 'futurefortunetasks.firebasestorage.app',
    iosBundleId: 'com.example.futureFortuneTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDKqdObNlaPBt5y3LWCUBWVMNZo4JFV_I',
    appId: '1:701849516005:ios:f9138acadbce32ab28210c',
    messagingSenderId: '701849516005',
    projectId: 'futurefortunetasks',
    storageBucket: 'futurefortunetasks.firebasestorage.app',
    iosBundleId: 'com.example.futureFortuneTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHldadrDpSpRw6vHAn0gErCreo2TpZHBA',
    appId: '1:701849516005:web:1f4e143e5d05d77628210c',
    messagingSenderId: '701849516005',
    projectId: 'futurefortunetasks',
    authDomain: 'futurefortunetasks.firebaseapp.com',
    storageBucket: 'futurefortunetasks.firebasestorage.app',
  );

}